version: '3.8'

services:
  web:
    build: .
    command: gunicorn frontend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web